export const TYPE_STORE_FORM_EDIT_MODE = "STORE_FORM_EDIT_MODE";
export const TYPE_STORE_ACCOUNT_DATA = "STORE_ACCOUNT_DATA";

export const TYPE_STORE_FNAME_TEMP = "STORE_FNAME_TEMP";
export const TYPE_STORE_LNAME_TEMP = "STORE_LNAME_TEMP";
export const TYPE_STORE_EMAIL_TEMP = "STORE_EMAIL_TEMP";
export const TYPE_STORE_DOB_TEMP = "STORE_DOB_TEMP";
export const TYPE_STORE_BIO_TEMP = "STORE_BIO_TEMP";
export const TYPE_STORE_PHONE_TEMP = "STORE_PHONE_TEMP";

export const TYPE_STORE_FNAME_ERROR_FLAG = "STORE_FNAME_ERROR_FLAG";
export const TYPE_STORE_LNAME_ERROR_FLAG = "STORE_LNAME_ERROR_FLAG";
export const TYPE_STORE_EMAIL_ERROR_FLAG = "STORE_EMAIL_ERROR_FLAG";
export const TYPE_STORE_DOB_ERROR_FLAG = "STORE_DOB_ERROR_FLAG";
export const TYPE_STORE_BIO_ERROR_FLAG = "STORE_BIO_ERROR_FLAG";
export const TYPE_STORE_PHONE_ERROR_FLAG = "STORE_PHONE_ERROR_FLAG";
